export const mockCompanies = [
  {
    id: 1,
    name: "TechCorp Solutions",
    industry: "Technology",
    location: "San Francisco, CA",
    size: "500-1000",
    founded: 2015,
    website: "techcorp.com",
    description: "Leading provider of enterprise software solutions",
  },
  {
    id: 2,
    name: "FinanceHub Inc",
    industry: "Finance",
    location: "New York, NY",
    size: "1000-5000",
    founded: 2010,
    website: "financehub.com",
    description: "Digital banking and financial services platform",
  },
  {
    id: 3,
    name: "HealthFirst Medical",
    industry: "Healthcare",
    location: "Boston, MA",
    size: "250-500",
    founded: 2018,
    website: "healthfirst.com",
    description: "Telemedicine and healthcare technology",
  },
  {
    id: 4,
    name: "EduLearn Platform",
    industry: "Education",
    location: "Austin, TX",
    size: "100-250",
    founded: 2020,
    website: "edulearn.com",
    description: "Online learning and education technology",
  },
  {
    id: 5,
    name: "GreenEnergy Co",
    industry: "Energy",
    location: "Seattle, WA",
    size: "250-500",
    founded: 2016,
    website: "greenenergy.com",
    description: "Renewable energy solutions",
  },
  {
    id: 6,
    name: "RetailMax",
    industry: "Retail",
    location: "Chicago, IL",
    size: "5000+",
    founded: 2005,
    website: "retailmax.com",
    description: "E-commerce and retail technology",
  },
  {
    id: 7,
    name: "CloudSystems Pro",
    industry: "Technology",
    location: "San Francisco, CA",
    size: "250-500",
    founded: 2019,
    website: "cloudsystems.com",
    description: "Cloud infrastructure and DevOps",
  },
  {
    id: 8,
    name: "MediaStream Inc",
    industry: "Media",
    location: "Los Angeles, CA",
    size: "500-1000",
    founded: 2014,
    website: "mediastream.com",
    description: "Digital media and streaming services",
  },
  {
    id: 9,
    name: "AutoDrive Tech",
    industry: "Automotive",
    location: "Detroit, MI",
    size: "1000-5000",
    founded: 2012,
    website: "autodrive.com",
    description: "Autonomous vehicle technology",
  },
  {
    id: 10,
    name: "FoodDelivery Plus",
    industry: "Food & Beverage",
    location: "Miami, FL",
    size: "250-500",
    founded: 2017,
    website: "fooddelivery.com",
    description: "Food delivery and restaurant technology",
  },
  {
    id: 11,
    name: "DataAnalytics Pro",
    industry: "Technology",
    location: "Seattle, WA",
    size: "100-250",
    founded: 2021,
    website: "dataanalytics.com",
    description: "Business intelligence and analytics",
  },
  {
    id: 12,
    name: "InsureTech Solutions",
    industry: "Finance",
    location: "Boston, MA",
    size: "500-1000",
    founded: 2013,
    website: "insuretech.com",
    description: "Insurance technology platform",
  },
  {
    id: 13,
    name: "SportsFit Gear",
    industry: "Retail",
    location: "Portland, OR",
    size: "100-250",
    founded: 2019,
    website: "sportsfit.com",
    description: "Athletic wear and sports equipment",
  },
  {
    id: 14,
    name: "SmartHome Innovations",
    industry: "Technology",
    location: "Austin, TX",
    size: "250-500",
    founded: 2018,
    website: "smarthome.com",
    description: "IoT and smart home devices",
  },
  {
    id: 15,
    name: "BioPharm Research",
    industry: "Healthcare",
    location: "San Diego, CA",
    size: "500-1000",
    founded: 2011,
    website: "biopharm.com",
    description: "Pharmaceutical research and development",
  },
  {
    id: 16,
    name: "TravelBooking Express",
    industry: "Travel",
    location: "Denver, CO",
    size: "250-500",
    founded: 2016,
    website: "travelbooking.com",
    description: "Travel booking and tourism platform",
  },
  {
    id: 17,
    name: "CyberSecurity Shield",
    industry: "Technology",
    location: "Washington, DC",
    size: "500-1000",
    founded: 2015,
    website: "cybersecurity.com",
    description: "Cybersecurity and threat protection",
  },
  {
    id: 18,
    name: "Fashion Forward",
    industry: "Retail",
    location: "New York, NY",
    size: "1000-5000",
    founded: 2008,
    website: "fashionforward.com",
    description: "Fashion e-commerce and design",
  },
  {
    id: 19,
    name: "AgriTech Farms",
    industry: "Agriculture",
    location: "Des Moines, IA",
    size: "100-250",
    founded: 2020,
    website: "agritech.com",
    description: "Agricultural technology and farming solutions",
  },
  {
    id: 20,
    name: "PropTech Realty",
    industry: "Real Estate",
    location: "Phoenix, AZ",
    size: "250-500",
    founded: 2017,
    website: "proptech.com",
    description: "Real estate technology platform",
  },
];

// Extract unique values for filters
export const getUniqueLocations = () => {
  return [...new Set(mockCompanies.map((c) => c.location))].sort();
};

export const getUniqueIndustries = () => {
  return [...new Set(mockCompanies.map((c) => c.industry))].sort();
};

export const getUniqueSizes = () => {
  return [...new Set(mockCompanies.map((c) => c.size))].sort();
};
